name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: a11y
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install NPM dependencies
        run: npm install

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build and start up jekyll server
        run: npm run build && npm run start-detached

      - name: Test accessibility
        run: "npm run test-a11y"
